### ISSUE TITLE
Defining rules in the hidden layer

### ISSUE THREAD

**Issue by sreejith3534** [kenoma/KerasFuzzy#1]
Hi,
How can i specify rules into the hidden layer?
also where are this antecedent and consequent ?

**Comment by kenoma** [comment]
Hi!

> How can i specify rules into the hidden layer?

You can specify rules for fuzzy layer via `initializer_centers` and `initializer_sigmas` (see `case5_iris_dataset.py` for details). I have no problems with setting `FuzzyLayer` as hidden layer. 

> also where are this antecedent and consequent ?

`FuzzyLayer` class provide antecedent part of fuzzy inference pipeline, you should combine it with `DefuzzyLayer` to get consequence according to common fis approach.
